In [1]:
import numpy as np

# Create a 2D numpy array with shape (4, 5)
array = np.random.uniform(0, 1, size=(4, 5))

# Print the resulting numpy array
print(array)


[[0.95549817 0.08018805 0.4772523  0.0287228  0.10929858]
 [0.27259751 0.59062462 0.6596189  0.85327848 0.35551534]
 [0.19310185 0.43776026 0.0822287  0.86036023 0.35707103]
 [0.25846134 0.50338048 0.61219231 0.28626164 0.23985996]]
